export interface Melody {
  id: string;
  name: string;
  emoji: string;
  notes: { note: string; duration: number }[];
}

export const MELODIES: Melody[] = [
  {
    id: "fur-elise",
    name: "Фур Элиз",
    emoji: "🎶",
    notes: [
      { note: "E5", duration: 0.25 },
      { note: "D#5", duration: 0.25 },
      { note: "E5", duration: 0.25 },
      { note: "D#5", duration: 0.25 },
      { note: "E5", duration: 0.25 },
      { note: "B4", duration: 0.25 },
      { note: "D5", duration: 0.25 },
      { note: "C5", duration: 0.25 },
      { note: "A4", duration: 0.5 },
      { note: "C4", duration: 0.25 },
      { note: "E4", duration: 0.25 },
      { note: "A4", duration: 0.25 },
      { note: "B4", duration: 0.5 },
      { note: "E4", duration: 0.25 },
      { note: "G#4", duration: 0.25 },
      { note: "B4", duration: 0.25 },
      { note: "C5", duration: 0.5 },
      { note: "E4", duration: 0.25 },
      { note: "E5", duration: 0.25 },
      { note: "D#5", duration: 0.25 },
      { note: "E5", duration: 0.25 },
      { note: "D#5", duration: 0.25 },
      { note: "E5", duration: 0.25 },
      { note: "B4", duration: 0.25 },
      { note: "D5", duration: 0.25 },
      { note: "C5", duration: 0.25 },
      { note: "A4", duration: 0.5 },
    ],
  },
  {
    id: "minuet",
    name: "Минутка (Bach)",
    emoji: "🎻",
    notes: [
      { note: "G4", duration: 0.4 },
      { note: "A4", duration: 0.2 },
      { note: "B4", duration: 0.2 },
      { note: "C5", duration: 0.4 },
      { note: "D5", duration: 0.2 },
      { note: "C5", duration: 0.2 },
      { note: "B4", duration: 0.4 },
      { note: "A4", duration: 0.2 },
      { note: "G4", duration: 0.2 },
      { note: "A4", duration: 0.4 },
      { note: "G4", duration: 0.2 },
      { note: "F#4", duration: 0.2 },
      { note: "G4", duration: 0.4 },
      { note: "A4", duration: 0.2 },
      { note: "B4", duration: 0.2 },
      { note: "G4", duration: 0.6 },
    ],
  },
  {
    id: "jingle-bells",
    name: "Jingle Bells",
    emoji: "🔔",
    notes: [
      { note: "E4", duration: 0.3 },
      { note: "E4", duration: 0.3 },
      { note: "E4", duration: 0.6 },
      { note: "E4", duration: 0.3 },
      { note: "E4", duration: 0.3 },
      { note: "E4", duration: 0.6 },
      { note: "E4", duration: 0.3 },
      { note: "G4", duration: 0.3 },
      { note: "C4", duration: 0.3 },
      { note: "D4", duration: 0.6 },
      { note: "E4", duration: 0.6 },
      { note: "F4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "E4", duration: 0.3 },
      { note: "E4", duration: 0.3 },
      { note: "E4", duration: 0.15 },
      { note: "E4", duration: 0.15 },
      { note: "E4", duration: 0.3 },
      { note: "G4", duration: 0.3 },
      { note: "G4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "D4", duration: 0.3 },
      { note: "C4", duration: 0.6 },
    ],
  },
  {
    id: "tetris",
    name: "Тетрис (Korobeiniki)",
    emoji: "🧱",
    notes: [
      { note: "E5", duration: 0.4 },
      { note: "B4", duration: 0.2 },
      { note: "C5", duration: 0.2 },
      { note: "D5", duration: 0.4 },
      { note: "C5", duration: 0.2 },
      { note: "B4", duration: 0.2 },
      { note: "A4", duration: 0.4 },
      { note: "A4", duration: 0.2 },
      { note: "C5", duration: 0.2 },
      { note: "E5", duration: 0.4 },
      { note: "D5", duration: 0.2 },
      { note: "C5", duration: 0.2 },
      { note: "B4", duration: 0.4 },
      { note: "C5", duration: 0.2 },
      { note: "D5", duration: 0.4 },
      { note: "E5", duration: 0.4 },
      { note: "C5", duration: 0.4 },
      { note: "A4", duration: 0.4 },
      { note: "A4", duration: 0.8 },
    ],
  },
  {
    id: "pirates",
    name: "Пираты Карибского моря",
    emoji: "🏴‍☠️",
    notes: [
      { note: "A4", duration: 0.3 },
      { note: "D4", duration: 0.6 },
      { note: "F4", duration: 0.3 },
      { note: "A4", duration: 0.3 },
      { note: "G4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "E4", duration: 0.3 },
      { note: "D4", duration: 0.6 },
      { note: "G4", duration: 0.3 },
      { note: "B4", duration: 0.3 },
      { note: "A4", duration: 0.3 },
      { note: "G4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "E4", duration: 0.6 },
      { note: "A4", duration: 0.3 },
      { note: "D4", duration: 0.6 },
      { note: "F4", duration: 0.3 },
      { note: "A4", duration: 0.3 },
      { note: "G4", duration: 0.3 },
      { note: "F4", duration: 0.3 },
      { note: "E4", duration: 0.3 },
      { note: "D4", duration: 0.6 },
    ],
  },
];
